// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqB55dTy3a2lvVo0ncpdu7GN2GQTfPAiM',
    appId: '1:22925091897:web:1f41e893845e786baf59e8',
    messagingSenderId: '22925091897',
    projectId: 'assignment-deadline-trac-7db81',
    authDomain: 'assignment-deadline-trac-7db81.firebaseapp.com',
    storageBucket: 'assignment-deadline-trac-7db81.firebasestorage.app',
    measurementId: 'G-XPJHPEJ0P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZy3yc7LtfMT1FyoUOGfFPULQO_xn2hls',
    appId: '1:22925091897:android:36082fbf62156939af59e8',
    messagingSenderId: '22925091897',
    projectId: 'assignment-deadline-trac-7db81',
    storageBucket: 'assignment-deadline-trac-7db81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlIscQ-s2ws3ja8n39ym5Zg8IMXwa0-a0',
    appId: '1:22925091897:ios:9e793a439d2729d2af59e8',
    messagingSenderId: '22925091897',
    projectId: 'assignment-deadline-trac-7db81',
    storageBucket: 'assignment-deadline-trac-7db81.firebasestorage.app',
    iosBundleId: 'com.example.assignmentDeadlineTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlIscQ-s2ws3ja8n39ym5Zg8IMXwa0-a0',
    appId: '1:22925091897:ios:9e793a439d2729d2af59e8',
    messagingSenderId: '22925091897',
    projectId: 'assignment-deadline-trac-7db81',
    storageBucket: 'assignment-deadline-trac-7db81.firebasestorage.app',
    iosBundleId: 'com.example.assignmentDeadlineTracker',
  );
}
